### ISSUE TITLE
React Icons

### ISSUE THREAD

**Issue by msclal** [UCR-CS110-S23/project-methinks#13]
install react-icons
and put the icons 

![Image](https://user-images.githubusercontent.com/60799725/238106749-1349216c-3d56-4564-a5f1-763ccf5aae76.png)

![Image](https://user-images.githubusercontent.com/60799725/238106781-e5a526d1-2271-4742-8115-ddad5e6671a8.png)

![Image](https://user-images.githubusercontent.com/60799725/238106788-0a46b476-381b-41aa-8dfe-98d5848585d8.png)

![Image](https://user-images.githubusercontent.com/60799725/238106830-1e5478fa-36e5-4015-8c3e-4f742e78969a.png)

**Comment by Yash8840** [comment]
Hey, can you assign it to me
