### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by msclal** [UCR-CS110-S23/project-methinks#8]
![Image](https://user-images.githubusercontent.com/60799725/237683689-01e1fdaf-d235-448d-8634-fa70c7fc2123.png)

put the code in ````Navigation.jsx```
call the component in ```Post.jsx```

**Comment by kliang622** [comment]
![image](https://github.com/UCR-CS110-S23/project-methinks/assets/66893422/bfe18548-9790-4aca-82f3-466ca840c188)
Doggo is a static place holder

**Comment by kliang622** [comment]
![image](https://github.com/UCR-CS110-S23/project-methinks/assets/66893422/8e3973d1-190b-4648-90f9-98ee511d4e9f)
- PFP is a static place holder
